version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dealer_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password_123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_strong_password_123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 20

  redis:
    image: redis:6-alpine
    container_name: dealer_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mssql_data:
    driver: local
